tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'homebrew/services'

brew 'rbenv'
brew 'ruby-build'
brew 'redis', restart_service: true
brew 'postgres', restart_service: true
brew 'heroku-toolbelt'
brew 'zsh-completions'
brew 'git'
brew 'kdiff3'
brew 'carthage'
brew 'tree'
brew 'chisel'

cask 'alfred'
cask 'dropbox'
cask 'gitx'
cask 'hex-fiend'
cask 'omnidisksweeper'
cask 'reveal'
cask 'sublime-text'
cask 'vmware-fusion'
cask 'hammerspoon'
