alias o='open .'
alias gco='git checkout'
alias gs='git status'
alias gx='git log --oneline --graph --decorate'
alias ..='cd ..'
alias be='bundle exec'
alias a='atom -n .'
alias gsmu='git submodule update --init --recursive'
